from pydantic import BaseModel


class RevealWord(BaseModel):
    """
    Response schema for revealing the generated word

    Attributes:
        revealWordResponse (str): The Burmese word generated by the model.
    """

    revealWordResponse: str

class PlayRequest(BaseModel):
    content: str
    count_round: str

class ImposterRequest(BaseModel):
    content: str 
    count_round: str

class HumanRequest(BaseModel):
    content: str 
